# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      force:
        description: 'Force Update'
        required: false
        default: 'false'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Version
      id: check
      run: |
        DATA=$(git ls-remote  https://github.com/v2fly/domain-list-community HEAD | head -n 1 | cut -f1)
        GFW=$(git ls-remote  https://github.com/gfwlist/gfwlist/ HEAD | head -n 1 | cut -f1)
        echo "$DATA"
        echo "$GFW"
        echo "DATA_GFW=${{DATA}}_${{GFW}}" >> $GITHUB_ENV
    - name: Check Version
      if: env.DATA_GFW != vars.DATA_SHA || ( github.event.inputs.force != 'false' && github.event.inputs.force != '')
      run: |
        echo "JIXU=true" >> $GITHUB_ENV      
           
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      if: env.JIXU == 'true'
      with:
        dotnet-version: 6.0.x
    - name: Restore And Build
      if: env.JIXU == 'true'
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
    - name: Checkout v2fly/domain-list-community
      uses: actions/checkout@v4
      if: env.JIXU == 'true'
      with:
        repository: v2fly/domain-list-community
        path: community
    - name: Checkout cokebar/gfwlist2dnsmasq
      uses: actions/checkout@v4
      if: env.JIXU == 'true'
      with:
        repository: cokebar/gfwlist2dnsmasq
        path: gfwlist2dnsmasq
    - name: Generate GFWList domains
      if: env.JIXU == 'true'
      run: |
        cd gfwlist2dnsmasq || exit 1
        chmod +x ./gfwlist2dnsmasq.sh
        ./gfwlist2dnsmasq.sh -l -o ../community/data/gfwlist
    - name: Update_SHA
      uses: NikhilVashistha/update-github-action-secret@v1.0.3
      if: env.JIXU == 'true'
      with:
        github_token: ${{ secrets.TOKEN }}
        variable: true
        variable_name: 'DATA_SHA'
        variable_value: ${{ env.DATA_GFW }}
    - name: Run
      if: env.JIXU == 'true'
      run: |
         dotnet ./gfwsites/bin/Release/net8.0/gfwsites.dll ./config.json ./community/data
    - name: Generate release tag
      id: tag
      if: env.JIXU == 'true'
      run: |
        touch release.txt
        echo "$(date +"%Y.%m.%d-%H%M")" >> release.txt
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        cd save
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: env.JIXU == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      if: env.JIXU == 'true'
      with:
        retain_days: 3
        keep_minimum_runs: 5
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      if: env.JIXU == 'true'
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
